name: lambda
on:
  push:
    branches:
      - main
    paths:
      - "data/lambda.py"
      - "data/requirements.txt"
      - "data/package*.json"
      - "data/serverless.yml"
      - ".github/workflows/lambda.yml"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        # Force due Serverless v4 clash with the plugins
        run: npm ci -f
        working-directory: ./data
      - name: Deploy
        run: npm run deploy
        working-directory: ./data
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          FILENAME: ${{ secrets.FILENAME }}
